name: Playwright Tests (Python)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python -m playwright install ${{ matrix.browser }}
      - run: pytest -q
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts-${{ matrix.browser }}
          path: artifacts/

  docker-run:
    runs-on: ubuntu-latest
    needs: test-matrix
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t playwright-python:latest .
      - run: docker run --rm playwright-python:latest
